### ISSUE TITLE
Launcher opens instead of game

### ISSUE THREAD

**Issue by Bud2k** [michalani/valorant-script-for-afk-xp-grind#12]
Hi,

When running the script, the launcher opens 50% of the time instead of the game. I'll have to click play first, then alt+f4 and reopen the script. Is there any fix?

Thanks

**Comment by michalani** [comment]
Sorry, I have no clue what could be causing that for you. What I would do on your place is locate valorants icon something like "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Riot Games" right click and get properties of it, and copy and replace the contents of valorant_location variable in the script.

**Comment by Bud2k** [comment]
> Sorry, I have no clue what could be causing that for you. What I would do on your place is locate valorants icon something like "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Riot Games" right click and get properties of it, copy info from target and replace the contents of valorant_location variable in the script.

I think that fixed it for me. I've launched the script about 6 times and the launcher hasn't opened once. Thanks a lot!
