### ISSUE TITLE
custom game modes

### ISSUE THREAD

**Issue by d1ret** [michalani/valorant-script-for-afk-xp-grind#3]
downloaded the new version, launched it, tested it, everything was done quite well (I used an autoclicker to select a new character, (I tried to somehow implement it in the code, but it doesn't work)
After he finishes the game, for some reason he does not find a new game
How fix it?
I have video, if u need i can load on youtube and give link

**Comment by michalani** [comment]
Yeah, custom game modes are not supported and I don't have any plans on adding it myself as it has the capability to fully kill the game.
