### ISSUE TITLE
Agents pick

### ISSUE THREAD

**Issue by malakhov-beep** [michalani/valorant-script-for-afk-xp-grind#4]
Hi, can you add autopick agents for spike rush?
and for some reason he doesn't start a new game after the end of the death match

**Comment by michalani** [comment]
Sorry, as said in issue https://github.com/michalani/valorant-script-for-afk-xp-grind/issues/3 I am not planning on adding such feature, you are welcome to add it yourself at any time you want.

**Comment by malakhov-beep** [comment]
Okay, can you fix the fact that he doesn't start searching for a new match after the previous one is over?

**Comment by michalani** [comment]
I am not a magician if you tell me more and provide pictures only then I might be able to help.

**Comment by malakhov-beep** [comment]
> I am not a magician if you tell me more and provide pictures only then I might be able to help.

sry me, I used Nvidia filters, added saturation for Valorant, and because of this, it did not click on the "PLAY AGAIN" button, as soon as I removed the saturation, it began to click on the button on its own
