### ISSUE TITLE
small correction in the code for exe file 

### ISSUE THREAD

**Issue by malakhov-beep** [michalani/valorant-script-for-afk-xp-grind#6]
Hi, it seems to me there is an error in your code (which is in the exe file), the user cannot set the gamemode

eg:
```
print(' 0 = unrated ')
print('1 = comp')
print('2 = spike rush')
print('3 = deathmatch ')
a = int(input("Please enter a number between 0 and 3:"))
gamemode = a
```

my knowledge in python leaves much to be desired, so it is possible that what I suggested is not correct at all

**Comment by michalani** [comment]
This shouldn't be changed as the script doesn't support other game modes. I've made it with future backwards compatibility in mind if someone wants to add their own game modes they are welcome to.
